const words = [
    { word: "algorithm", hint: "A step-by-step procedure for solving a problem" },
    { word: "binary", hint: "A numbering system using only 0 and 1" },
    { word: "variable", hint: "A storage location in programming that holds data" },
    { word: "function", hint: "A block of code designed to perform a task" },
    { word: "array", hint: "A collection of items stored at contiguous memory locations" },
    { word: "object", hint: "An instance of a class containing data and methods" },
    { word: "string", hint: "A sequence of characters" },
    { word: "loop", hint: "A control structure used for repeating code" },
    { word: "database", hint: "A structured set of data held in a computer" },
    { word: "server", hint: "A computer that provides data to other computers" },
    { word: "client", hint: "A computer or software that requests services" },
    { word: "framework", hint: "A platform for developing software applications" },
    { word: "API", hint: "A set of functions for interacting with software components" },
    { word: "compiler", hint: "A program that translates code into machine language" },
    { word: "recursion", hint: "A function that calls itself" },
    { word: "syntax", hint: "The set of rules that defines code structure" },
    { word: "debugging", hint: "The process of identifying and fixing errors in code" },
    { word: "iteration", hint: "The repetition of a process in a program" },
    { word: "encryption", hint: "The process of converting data into a secure format" },
    { word: "hashing", hint: "Transforming data into a fixed-size value or key" },
    { word: "authentication", hint: "Verifying the identity of a user or device" },
    { word: "protocol", hint: "A set of rules for data communication" },
    { word: "inheritance", hint: "A mechanism for creating a new class from an existing one" },
    { word: "constructor", hint: "A special function used to initialize objects" },
    { word: "closure", hint: "A function with access to its outer function scope" },
    { word: "module", hint: "A self-contained piece of code that can be reused" },
    { word: "callback", hint: "A function passed as an argument to another function" },
    { word: "middleware", hint: "Software that connects different applications" },
    { word: "JSON", hint: "A format for structuring data, stands for JavaScript Object Notation" },
    { word: "DOM", hint: "Document Object Model, a representation of the web page" },
    { word: "query", hint: "A request for data or information from a database" },
    { word: "null", hint: "Represents the absence of any value" },
    { word: "Boolean", hint: "A data type that can be either true or false" },
    { word: "asynchronous", hint: "Operations that occur independently of the main program flow" },
    { word: "promise", hint: "An object representing the eventual completion of an asynchronous operation" },
    { word: "event", hint: "An action or occurrence recognized by software" },
    { word: "constructor", hint: "A special method for creating and initializing objects" },
    { word: "parse", hint: "To analyze a string of data or code" },
    { word: "compile", hint: "To transform code into machine language" },
    { word: "integrate", hint: "To combine components into a unified system" },
    { word: "responsive", hint: "Design that adapts to different screen sizes" },
    { word: "debug", hint: "To find and fix bugs in a program" },
    { word: "stack", hint: "A data structure that follows Last In, First Out" },
    { word: "queue", hint: "A data structure that follows First In, First Out" },
    { word: "algorithm", hint: "A sequence of instructions to solve a problem" },
    { word: "iterate", hint: "To repeat a process or set of instructions" },
    { word: "token", hint: "A string of characters used for security or authentication" },
    { word: "session", hint: "A period during which a user interacts with an application" },
    { word: "cache", hint: "A hardware or software component that stores data for quick access" },
    { word: "virtual", hint: "Not physically existing but made by software" },
    { word: "firewall", hint: "A security system that monitors and controls network traffic" },
    { word: "gateway", hint: "A network point that acts as an entrance to another network" },
    { word: "router", hint: "A device that forwards data packets between networks" },
    { word: "bandwidth", hint: "The amount of data that can be transferred in a given time" },
    { word: "cloud", hint: "Storing and accessing data over the internet" },
    { word: "compression", hint: "Reducing the size of a file or data" },
    { word: "latency", hint: "The delay before a transfer of data begins following an instruction" },
    { word: "scalability", hint: "The ability of a system to handle increased workload" },
    { word: "migration", hint: "Moving data or software from one environment to another" },
    { word: "sandbox", hint: "A testing environment that isolates changes" },
    { word: "tokenization", hint: "The process of substituting sensitive data with unique identifiers" },
    { word: "container", hint: "A lightweight, standalone executable package" },
    { word: "microservice", hint: "A small, independent service that is part of a larger application" },
    { word: "Kubernetes", hint: "An open-source system for managing containerized applications" },
    { word: "Docker", hint: "A platform for developing, shipping, and running applications in containers" },
    { word: "graph", hint: "A data structure used to model pairwise relations between objects" },
    { word: "node", hint: "An element of a data structure, such as a linked list or tree" },
    { word: "edge", hint: "A connection between nodes in a graph" },
    { word: "queue", hint: "A collection of elements supporting First In, First Out operations" },
    { word: "stack", hint: "A collection of elements supporting Last In, First Out operations" },
    { word: "tree", hint: "A hierarchical data structure with nodes" },
    { word: "heap", hint: "A specialized tree-based data structure" },
    { word: "sort", hint: "Arranging data in a particular order" },
    { word: "search", hint: "Looking for an item in a collection of data" },
    { word: "priority", hint: "Order of importance in processing" },
    { word: "scheduling", hint: "Assigning tasks to resources in a time frame" },
    { word: "thread", hint: "A single sequence of executable instructions" },
    { word: "mutex", hint: "A program object that prevents multiple threads from accessing the same resource" },
    { word: "deadlock", hint: "A state where two or more threads are unable to proceed" },
    { word: "timeout", hint: "An event that occurs when a predefined time limit has been reached" },
    { word: "buffer", hint: "Temporary storage used to hold data while it is being transferred" },
    { word: "bit", hint: "The smallest unit of data in computing" },
    { word: "byte", hint: "A unit of data composed of 8 bits" },
    { word: "kilobyte", hint: "1024 bytes of data" },
    { word: "megabyte", hint: "1024 kilobytes of data" },
    { word: "gigabyte", hint: "1024 megabytes of data" },
    { word: "terabyte", hint: "1024 gigabytes of data" },
    { word: "petabyte", hint: "1024 terabytes of data" },
    { word: "exabyte", hint: "1024 petabytes of data" },
    { word: "hexadecimal", hint: "A base-16 numbering system using 0-9 and A-F" },
    { word: "octal", hint: "A base-8 numbering system using digits 0-7" },
    { word: "pointer", hint: "A variable that stores the memory address of another variable" },
    { word: "reference", hint: "An alias for another variable" },
    { word: "dynamic", hint: "Memory that is allocated during runtime" },
    { word: "static", hint: "Memory that is allocated at compile-time" },
    { word: "overflow", hint: "An error that occurs when data exceeds storage limits" },
    { word: "underflow", hint: "An error that occurs when a data structure is empty" },
    { word: "logic", hint: "Reasoning conducted according to strict principles of validity" },
    { word: "compile", hint: "To translate code from high-level language to machine code" },
    { word: "execute", hint: "To run a program or a set of instructions" },
    { word: "terminate", hint: "To end a process or program" },
    { word: "parse", hint: "To analyze a string of characters or data" },
    { word: "concatenate", hint: "To link or join strings together" },
    { word: "encrypt", hint: "To convert information into a secure format" },
    { word: "decrypt", hint: "To convert encrypted information back to readable form" },
    { word: "sanitize", hint: "To clean data to prevent security vulnerabilities" },
    { word: "validate", hint: "To check if data meets certain criteria" },
    { word: "compile", hint: "Convert code into executable format" },
    { word: "interpret", hint: "Execute code line by line without compiling" },
    { word: "bitwise", hint: "Operations that manipulate data at the binary level" },
    { word: "shift", hint: "Move bits left or right in a binary number" },
    { word: "mask", hint: "Use bitwise operations to extract specific bits" },
    { word: "overflow", hint: "An error caused by exceeding storage capacity" },
    { word: "underflow", hint: "An error caused by attempting to access below minimum capacity" },
    { word: "integral", hint: "A whole number value in programming" },
    { word: "floating", hint: "A number with a decimal point" },
    { word: "precision", hint: "The level of detail represented by a number" },
    { word: "rounding", hint: "Reducing the number of significant digits" },
    { word: "normalize", hint: "Adjust values to a common scale" },
    { word: "overflow", hint: "An error when calculations exceed storage limits" },
    { word: "truncate", hint: "To shorten a number by dropping digits" },
    { word: "serialize", hint: "Convert an object into a format that can be easily stored or transmitted" },
    { word: "deserialize", hint: "Convert serialized data back into an object" },
    { word: "boot", hint: "Start up a computer or program" },
    { word: "shutdown", hint: "Turn off a computer or program" },
    { word: "reboot", hint: "Restart a computer or program" },
    { word: "snapshot", hint: "A saved state of a system at a particular time" },
    { word: "backup", hint: "A copy of data stored for recovery" },
    { word: "restore", hint: "To bring back a saved state of data" },
    { word: "emulator", hint: "Software that mimics another environment" },
    { word: "virtualization", hint: "Creating a virtual version of a physical resource" },
    { word: "host", hint: "A computer that provides resources" },
    { word: "guest", hint: "A virtual machine running on a host" },
    { word: "hypervisor", hint: "Software that creates and manages virtual machines" },
    { word: "cluster", hint: "A group of linked computers that work together" },
    { word: "node", hint: "A device or data point in a larger network" },
    { word: "protocol", hint: "A set of rules governing data exchange" },
    { word: "handshake", hint: "An initial connection between two devices" },
  ];
  